import { Roboto } from "next/font/google";
import { Kosugi } from "next/font/google";
import styles from "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import Providers from "./components/providers";

const roboto = Roboto({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
  weight: ["100", "300", "400", "500", "700", "900"],
});

const kosugi = Kosugi({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-kosugi",
  weight: ["400"],
});

export const metadata = {
  title: "INUKKORO®",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body id="hi" className={`${roboto.className} ${kosugi.className}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
